%% Generated by tgif2tex version 2.13
%% Original: delete1.ps page 1
\unitlength 1pt
\begin{picture}(186,133)
\put(0,0){\special{PSfile=./delete1.dps llx=126 lly=615 urx=312 ury=748 rwi=1860}}
\put(38.2,76.8){\makebox(0,0)[lb]{{\Large $1{\color{red}\underline{1}}$}}}
\put(15.8,11.5){\makebox(0,0)[lb]{{\Large $00$}}}
\put(58.5,11.5){\makebox(0,0)[lb]{{\Large $1$}}}
\put(92.2,9.2){\makebox(0,0)[lb]{{\Large $\phi$}}}
\put(90.0,115.0){\makebox(0,0)[lb]{{\Large Root Node}}}
\end{picture}
