%% Generated by tgif2tex version 2.13
%% Original: simple3.ps page 1
\unitlength 1pt
\begin{picture}(85,96)
\put(0,0){\special{PSfile=./simple3.dps llx=50 lly=712 urx=135 ury=808 rwi=850}}
\put(36.6,14.1){\makebox(0,0)[lb]{{\Large $\color{red}{\underline{R_{1}^{2}}}$}}}
\put(27.6,61.3){\makebox(0,0)[lb]{{\Large $\color{red}{1}$}}}
\put(2.9,86.1){\makebox(0,0)[lb]{{\Large $T_{3}$}}}
\end{picture}
