%% Generated by tgif2tex version 2.13
%% Original: rightarrow.ps page 1
\unitlength 1pt
\begin{picture}(58,27)
\put(0,0){\special{PSfile=./rightarrow.dps llx=63 lly=703 urx=121 ury=730 rwi=580}}
\end{picture}
